---
apiVersion: v1
items:
kind: List
metadata: {}
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: CHANGE_ME-CHANGE_ME-__BRANCH__
      chart: CHANGE_ME-CHANGE_ME-__BRANCH__-0.0.1
      heritage: Tiller
      release: CHANGE_ME-CHANGE_ME-__BRANCH__
    name: CHANGE_ME-CHANGE_ME-__BRANCH__
    namespace: __PROJECT__
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: CHANGE_ME-CHANGE_ME-__BRANCH__
    template:
      metadata:
        labels:
          app: CHANGE_ME-CHANGE_ME-__BRANCH__
          release: CHANGE_ME-CHANGE_ME-__BRANCH__
      spec:
        imagePullSecrets:
        - name: docker-registry-credentials
        containers:
          - name: CHANGE_ME-CHANGE_ME-__BRANCH__
            image: "__IMAGE_TAG__"
            imagePullPolicy: "Always"
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            livenessProbe:
              tcpSocket:
                port: http
              initialDelaySeconds: 600
              timeoutSeconds: 60
            readinessProbe:
              tcpSocket:
                port: http
            resources:
              {}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: CHANGE_ME-CHANGE_ME-__BRANCH__
      chart: CHANGE_ME-CHANGE_ME-__BRANCH__-0.0.1
      heritage: Tiller
      release: CHANGE_ME-CHANGE_ME-__BRANCH__
      version: v1
    name: CHANGE_ME-CHANGE_ME-__BRANCH__
    namespace: __PROJECT__
  spec:
    type: "ClusterIP"
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
    selector:
      app: CHANGE_ME-CHANGE_ME-__BRANCH__
      release: CHANGE_ME-CHANGE_ME-__BRANCH__
