---
apiVersion: v1
items:
kind: List
metadata: {}
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: green-redcloud3-gs-uploading-files-__BRANCH__
      chart: green-redcloud3-gs-uploading-files-__BRANCH__-0.0.1
      heritage: Tiller
      release: green-redcloud3-gs-uploading-files-__BRANCH__
    name: green-redcloud3-gs-uploading-files-__BRANCH__
    namespace: __PROJECT__
  spec:
    replicas: 1
    selector:
      deploymentconfig: green-redcloud3-gs-uploading-files-__BRANCH__
    template:
      metadata:
        labels:
          app: green-redcloud3-gs-uploading-files-__BRANCH__
          release: green-redcloud3-gs-uploading-files-__BRANCH__
          deploymentconfig: green-redcloud3-gs-uploading-files-__BRANCH__
          version: v1
      spec:
        imagePullSecrets:
        - name: docker-registry-credentials
        containers:
          - name: green-redcloud3-gs-uploading-files-__BRANCH__
            image: "__IMAGE_TAG__"
            imagePullPolicy: "Always"
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            livenessProbe:
              tcpSocket:
                port: http
              initialDelaySeconds: 600
              timeoutSeconds: 60
            readinessProbe:
              tcpSocket:
                port: http
            resources:
              {}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: green-redcloud3-gs-uploading-files-__BRANCH__
      chart: green-redcloud3-gs-uploading-files-__BRANCH__-0.0.1
      heritage: Tiller
      release: green-redcloud3-gs-uploading-files-__BRANCH__
      version: v1
    name: green-redcloud3-gs-uploading-files-__BRANCH__
    namespace: __PROJECT__
  spec:
    type: "ClusterIP"
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
    selector:
      app: green-redcloud3-gs-uploading-files-__BRANCH__
      release: green-redcloud3-gs-uploading-files-__BRANCH__
